thirdparties:
    amazon:
        key: ""
        secret: ""
    battlenet:
        key: ""
        secret: ""
    bitbucket:
        key: ""
        secret: ""
    bitly:
        key: ""
        secret: ""
    bitrix24:
        key: ""
        secret: ""
    box:
        key: ""
        secret: ""
    buffer:
        key: ""
        secret: ""
    dailymotion:
        key: ""
        secret: ""
    delicious:
        key: ""
        secret: ""
    deezer:
        key: ""
        secret: ""
    deviantart:
        key: ""
        secret: ""
    dropbox:
        key: ""
        secret: ""
    etsy:
        key: ""
        secret: ""
    eveonline:
        key: ""
        secret: ""
    facebook:
        key: ""
        secret: ""
    fitbit:
        key: ""
        secret: ""
    fivehundredpx:
        key: ""
        secret: ""
    flickr:
        key: ""
        secret: ""
    foursquare:
        key: ""
        secret: ""
    github:
        key: ""
        secret: ""
    google:
        key: ""
        secret: ""
    hubic:
        key: ""
        secret: ""
    instagram:
        key: ""
        secret: ""
    linkedin:
        key: ""
        secret: ""
    mailchimp:
        key: ""
        secret: ""
    microsoft:
        key: ""
        secret: ""
    mondo:
        key: ""
        secret: ""
    nest:
        key: ""
        secret: ""
    netatmo:
        key: ""
        secret: ""
    parrotFlowerPower:
        key: ""
        secret: ""
    paypal:
        key: ""
        secret: ""
    pinterest:
        key: ""
        secret: ""
    pocket:
        key: ""
        secret: ""
    quickbooks:
        key: ""
        secret: ""
    reddit:
        key: ""
        secret: ""
    redmine:
        key: ""
        secret: ""
    runkeeper:
        key: ""
        secret: ""
    salesforce:
        key: ""
        secret: ""
    scoopit:
        key: ""
        secret: ""
    soundcloud:
        key: ""
        secret: ""
    spotify:
        key: ""
        secret: ""
    strava:
        key: ""
        secret: ""
    tumblr:
        key: ""
        secret: ""
    twitter:
        key: ""
        secret: ""
    ustream:
        key: ""
        secret: ""
    vimeo:
        key: ""
        secret: ""
    yahoo:
        key: ""
        secret: ""
    yammer:
        key: "test"
        secret: "test"
